### PR TITLE
chore(ci): Text and output adjustments

### PR DESCRIPTION
**Pull request by tobiasmllr**
# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-hydrometric-rating-curve-87-frontend.apps.silver.devops.gov.bc.ca/) available

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-hydrometric-rating-curve/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-hydrometric-rating-curve/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by DerekRoberts** [comment]
@tobiasmllr PR updated to fix the validator workflow!  Sorry, should be good now.

**Comment by tobiasmllr** [comment]
@DerekRoberts Thanks for working on this. It appears this still fails, but the reason seems very unspecific:

Using project "***".
Welcome! See 'oc help' to get started.
Already on project "***" on server "https://api.silver.devops.gov.bc.ca:6443/".
imagestream.image.openshift.io "nr-hydrometric-rating-curve-87-rctool" deleted
secret/nr-hydrometric-rating-curve-87-rctool configured
imagestream.image.openshift.io/nr-hydrometric-rating-curve-87-rctool created
deploymentconfig.apps.openshift.io/nr-hydrometric-rating-curve-87-rctool configured
service/nr-hydrometric-rating-curve-87-rctool unchanged
horizontalpodautoscaler.autoscaling/nr-hydrometric-rating-curve-87-rctool unchanged
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for latest deployment config spec to be observed by the controller loop...
Waiting for latest deployment config spec to be observed by the controller loop...
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
error: replication controller "nr-hydrometric-rating-curve-87-rctool-5" has failed progressing
Error: Process completed with exit code 1.

**Comment by DerekRoberts** [comment]
@tobiasmllr Are you very comfortable with OpenShift?

**Comment by DerekRoberts** [comment]
@tobiasmllr We were out of resources!  After clearing some junk this PR should be back on track.  Please pop onto Teams some time and we can talk about troubleshooting.  :)

**Pull request merged**
